### ISSUE TITLE
Improve documentation about 'Boostrap'

### ISSUE THREAD

**Issue by abelsromero** [ysb33r/gradleTest#20]
The section in the README about setting the plugin is missing the configuration of the maven repo and available versions (copying the example fails).

In my case I had to go an check https://github.com/jruby-gradle/jruby-gradle-plugin/blob/master/build.gradle to see an example of full configuration.

**Comment by ysb33r** [comment]
Would you mind creating a PR?

<div>-------- Original message --------</div><div>From: Abel Salgado Romero <notifications@github.com> </div><div>Date:24/08/2015  11:53  (GMT+00:00) </div><div>To: ysb33r/gradleTest <gradleTest@noreply.github.com> </div><div>Subject: [gradleTest] Improve documentation about 'Boostrap' (#20) </div><div>
</div>The section in the README about setting the plugin is missing the configuration of the maven repo and available versions (copying the example fails).

In my case I had to go an check https://github.com/jruby-gradle/jruby-gradle-plugin/blob/master/build.gradle to see an example of full configuration.

**Comment by abelsromero** [comment]
I was tempted to add a note about the new plugins DSL.
But I prefer not to mention it as long as it is an _incubating_ feature.

**Comment by abelsromero** [comment]
Corrected a typo and squashed
