### ISSUE TITLE
Tested plugin is not added as a buildscript dependency

### ISSUE THREAD

**Issue by szpak** [ysb33r/gradleTest#24]
As mentioned in README I expected to have my plugin added to buildscript dependencies. However it seems not to happen. The problem can be reproduced in the [issue/gradleTestDep](https://github.com/4finance/uptodate-gradle-plugin/tree/issue/gradleTestDep) branch of the uptodate-gradle-plugin project.

`gw gradleTest` displays no buildscript dependencies. The same uncommenting `apply plugin: 'com.ofg.uptodate'` generates the error.

Tested with 0.5.4.

**Comment by ysb33r** [comment]
Although it is in the README, maybe this is not quite clear. You need to tell `gradleTest` which depedencies to put in the local repository. So in your project's `build.gradle` add

```groovy
dependencies {
  gradleTest 'org.codehaus.groovy.modules.http-builder:http-builder:0.7.2'
}
```

This might look like you are repeating yourself, But I wanted to the script author to control what gets tested.

Then your `src/gradleTest/simple1/build.gradle`  can be simplied to 

```groovy
buildscript {
    dependencies {
        classpath 'com.ofg:uptodate-gradle-plugin:%%VERSION%%'
    }
}
```

Hey, this now works on my machine :-)

**Comment by szpak** [comment]
Yes, as this jar is put into flat repository in a `repo` dir. Thanks for clarification.
