### ISSUE TITLE
Dependency with %%VERSION%% does not include transive dependencies

### ISSUE THREAD

**Issue by szpak** [ysb33r/gradleTest#25]
When a dependency with `%%VERSION%%` is used it does not include transive dependencies. The execution fails with `ClassNotFoundException` when plugin tries to use its dependencies. Tested with 0.5.4.

**Comment by szpak** [comment]
That's probably because I take a jar from the `libs` directory, so there is no information about dependencies.

**Comment by szpak** [comment]
Anyone due to #24 it is hard to add itself as a dependency.

**Comment by szpak** [comment]
It would be probably good to allow to use dependencies defined in `gradleTest` configuration with their transitive dependencies (in the other case all of them need to be precised manually one-by-one, which is boring and hard to maintain when with the version number of transitive dependencies increase).

**Comment by ysb33r** [comment]
We could do that. From what I've leant from writing the ysb33r/ivypot plugin, I think it can be main to work so that offline testing can also work.

**Comment by szpak** [comment]
ivypot looks very interesting. It could be used to prepare offline repository (e.g. provided on pendrive) when training session is carried out in a place with poor internet connection.

**Comment by ysb33r** [comment]
FIxes in 1.0 eliminates the the need for `%%VERSION%%. There is some transitivie dependency testing that needs doing before 1.0 can be fully released.
