### ISSUE TITLE
gradleDistributionDownloader task could display progress on info

### ISSUE THREAD

**Issue by szpak** [ysb33r/gradleTest#27]
Currently `gradleDistributionDownloader` can take some time (especially when `downloadToGradleUserHome` is not set after `gw clean`). There could a message "Downloading <file name/path>..." displayed on INFO level just before every file is started to be downloaded.

**Comment by ysb33r** [comment]
`gradleDistributionDownloader` might be dropped if #33 is implemented.

**Comment by ysb33r** [comment]
#33 done which eliminates this one.
