### ISSUE TITLE
Unable to specify custom init script

### ISSUE THREAD

**Issue by szpak** [ysb33r/gradleTest#30]
It seems to be impossible to define custom initscript in a task configuration:

```
gradleTest {
    versions '2.12'
    initscript 'src/test/resources/myinit.gradle'   //or file(...)
}
```

results in:

```
* What went wrong:
A problem occurred evaluating root project 'uptodate-gradle-plugin'.
> Could not find method initscript() for arguments [src/test/resources/myinit.gradle] on root project 'uptodate-gradle-plugin'.
```

Looking at the source code it seems that there is only private filed `initScript`. When it is changed to public custom script is being loaded.

Anyway there is inconsistency with `initscript` (documentation) vs. `initScript` (init code).

**Comment by ysb33r** [comment]
Reopening after Appveyor failure.
