### ISSUE TITLE
Report Gradle version used to execute given test

### ISSUE THREAD

**Issue by szpak** [ysb33r/gradleTest#31]
Currently `simple1: PASSED/FAILED` is displayed. When running tests for multiple Gradle version in case of failure it could be hard to find output for test execution for given Gradle version. Gradle version could be included in those lines, e.g.:

```
Gradle 2.12: simple1: PASSED
```

**Comment by ysb33r** [comment]
We've been doing some work on this in #2 at Gr8Conf last year, but it was not completed. Subsequqntly `TestKit` came out and focus has swtiched to that. This will improve if #33 is implemented.
