### ISSUE TITLE
The TaskInputs.source(Object) method has been deprecated

### ISSUE THREAD

**Issue by scphantm** [ysb33r/gradleTest#50]
using the latest beta 4, whenever i run it with gradle 3.1 i get 

`The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.`

**Comment by ysb33r** [comment]
Fixed by 52a63ce7151618f88485a56a8a10e1bb704873b0. Will be in beta-5.
