### ISSUE TITLE
Classpath of multi project builds

### ISSUE THREAD

**Issue by scphantm** [ysb33r/gradleTest#51]
I am working on a whole suite of plugins.  I have them in a single project as a multi-module project.  Inside of this project is a simple jar that has code common to all plugins in the suite.  If i run GradleTest on one of the modules that requires the jar (brought in with `compile project(':myjar')` in the subprojects gradle.build then gradletest doesn't see the jar and it fails with class not found.

**Comment by ysb33r** [comment]
Although I think I have a good idea of the use-case, it would be worth seeing 
an example of what you are trying to achieve.

**Comment by scphantm** [comment]
```
project(':mylib'){
	
}

project(':plugin1'){
	dependencies {
	    compile project(':mylib')
	}
}

project(':plugin2'){
	dependencies {
	    compile project(':mylib')
	}
}
```

is more or less what i am doing.  when you run gradletest on plugin1, it doesn't bring mylib into the classpath and dies with a class not found.

**Comment by ysb33r** [comment]
@scphantm I have not yet written a test for this, but it might be that #57 that was part of the beta7 release solves it. Would you mind trying it and leting me know?

**Comment by ysb33r** [comment]
@scphantm I have added a test project `compatibility/src/gradleTest/multiPluginProject` that simulates the above layout. It seems to pass with the #57 fixes.  The code changeset is 34ce537.
