### ISSUE TITLE
Expected Failure case

### ISSUE THREAD

**Issue by scphantm** [ysb33r/gradleTest#52]
Sometimes the build failing is in itself a test pass.  For example  i have a plugin that is designed to blow up the build if a particular variable isn't set in the build file.  In this case, while testing it, i want to make sure that the build does indeed blow up if i don't set that variable.  Doesn't look like you can do that with this framework.

**Comment by ysb33r** [comment]
Yes, that is currently not supported. Will look into it.

**Comment by ysb33r** [comment]
I think we can present this in one of two ways

*Option 1:*: All tests in a group fails

```groovy
task failingTests (org.ysb33r.gradle.gradleTest){
  failureGroup
}
```

This will mean that one has to create separate groups for compatibility tests
that will pass and will fail

*Options 2:* Mark tests that will fail by pattern

```groovy
gradleTest {
  // Single string
  expectFailure 'testOne'

  // As a pattern
  expectFailure ~/TestFoo.+/
}
```

Currently I am leaning towards the second option. However, I could completely have
misinterpreted your use-case, so if so, feel free to explain it or point to to some 
code where it is required.

**Comment by scphantm** [comment]
i would lean towards the second as well.  seems far more flexible that way.

**Comment by ysb33r** [comment]
This is is fixed in 1-0.beta5.
