### ISSUE TITLE
Disable if folder not present

### ISSUE THREAD

**Issue by scphantm** [ysb33r/gradleTest#53]
In multi-project builds you may have one or two subprojects that do not need gradletest.  Therefore the gradleTest folder doesn't exist.  

In todays code the gradletest will fail the build saying the folder doesn't exist.  What it should do is quietly disable the plugin for that subproject, maybe print a warning that it has done so and move on.

**Comment by ysb33r** [comment]
This is also an inverse of #49

**Comment by ysb33r** [comment]
This is is fixed in 1-0.beta5.
