### ISSUE TITLE
Document alternatives

### ISSUE THREAD

**Issue by ysb33r** [ysb33r/gradleTest#60]
Write about:

- [x] GradleTestKit
- [x]  https://github.com/ajoberstar/gradle-stutter

**Comment by ysb33r** [comment]
Proposed text for `GradleTestKit`:

`GradleTestKit` is the core API that ships with Gradle since Gradle 2.6. which is meant for plugin developers to test compatibility across Gradle versions. Easrly versions could only tests against the same version of Gradle that was running, but it has been enhanced over different Gradle releases. Today it is powereful allowing multiple versions to be tested and a number of different environments to be set up.

It is also a core compoenent of `GradleTest` when the version of Gradle is 2.13 or later.  (When the current build version is older `GradleTest` falls back to legacy mode, simply because the `GradleTestKit` API either is non-existent or not mature enough.

`GradleTestKit` works well for integration testing when writing plugins if a select small group of Gradle versions are used or even if it only targets the current Gradle version. In this way one can quickly determine issues in a plugin which cannot be discovered via normal testing. `GradleTest` used `GradleTestKit` directly for its integration tests for exactly this reason. 

Testing multiple versions of Gradle with GradleTestKit soon bcomes a burden for developers as the API differs and classpath setups can be tricky. Older versions of Gradle give the most issues. In addition `GradleTestKit` is essentially a library it focuses on the developer rather than the build script user.

In this regard `GradleTest` steps in as it allow tests to be written as if a normal buildscript would be written. it also manages differences (or non-existance) in API from Gradle 2.0 onwards in a completely transparent way to the plugin author.

Overall the approach should be to write integration tests with `GradleTestKit` using a limited or even just one Gradle version. This is then complimented by some `GradleTest` scripts to test a wider range of Gradle versions.

**Comment by ysb33r** [comment]
Proposed text for `stutter`: (@ajoberstar - please comment).

Gradle Stutter is a library by Andy Oberstar to also aid with plugin development. It is essentially a mid-way between integration tests with `GradleTestKit` and fully-fledged test scripts with `GradleTest`. it removes some of the complexity of setting up the `GradleTestKit` environment, but only works from Gradle 2.13 onwards.

It adds a `compatTest` source set, which will not clash with the `gradleTest` source set from `GradleTest`. It also requires the use of `java-gradle-plugin`, which might not be something all plugin developers require, especially those who prefer Groovy or Kotlin as their language of choice for development.

I can however be an easy way to manage some more complex plugin integration tests.

**Comment by ajoberstar** [comment]
> It is essentially a mid-way point between integration tests with GradleTestKit and fully-fledged test scripts with GradleTest.

I don't think I would characterize GradleTestKit or Stutter as integration tests versus full-fledged tests. TestKit is running a full Gradle project/build and then giving you the opportunity to validate which tasks ran, validate console output, inspect the builds results. You can create the projects by either inling build scripts and files, or pointing to an existing project directory (like GradleTest does under the covers).

Besides the 2.13+ limitation, Stutter doesn't add any restrictions on top of GradleTestKit, it just tries to ease some of the boilerplate for some use cases I've found common.

I certainly may have missed something in my scan of your plugin, but my understanding is that GradleTest optimizes for creating sample projects and running a specific set of tasks against all of them. I didn't see a way to do any validation beyond "it successfully built".

And that is probably the crux of the difference between them:

- If you want to create good samples and make sure they build, GradleTest is a clear win. Not having to write the extra test code (or touch the TestKit API)  is a great benefit.
- If you need to validate what the build did, I think you're back in TestKit land and then maybe Stutter can make it easier for you.

>  It removes some of the complexity of setting up the GradleTestKit environment.

This is the main goal with Stutter. My normal use case is that I have the same tests I want to run against all supported versions, but I don't want to deal with making each test loop over those versions (or `@Unroll` with a `where` block in Spock). Stutter generates one task per supported version and you run the full set of tests against it.

I'll also be adding some helper classes to use in the tests:
- A method that does part of the `GradleRunner` setup for you, fills in the plugin classpath and fills in the gradle version.
- A method to check if the current Gradle version under test is >= or <= a certain version. This let's you use an `@OnlyIf` or JUnit assumption to exempt specific tests that don't work for certain Gradle versions.
- A method that copies a full test project into a temp dir for a single test.

> requires the use of java-gradle-plugin, which might not be something all plugin developers require, especially those who prefer Groovy or Kotlin

The `java-gradle-plugin` isn't Java specific (I usually write tests in Groovy). It's just the out-of-the-box Gradle plugin helper plugin. It helps with validation of your plugin ID properties files, among other things. My main reason to require it is that it will generate plugin classpath metadata for you which lets you use the `GradleRunner.withPluginClasspath()` method that auto configures the classpath to use your newly built plugin and it's dependencies. The one caveat is that only works if you test against 2.13 or higher.

**Comment by ysb33r** [comment]
@ajoberstar I've updated the proposed text above. See what you think of it.

**Comment by ajoberstar** [comment]
Makes sense on the helper stuff and looks good to me.

**Comment by ysb33r** [comment]
Fixed by ff168f7
