### ISSUE TITLE
Codenarc reports errors

### ISSUE THREAD

**Issue by scphantm** [ysb33r/gradleTest#65]
When you add gradleTest to a project that has codenarc configured, since gradleTest creates a sourceSet for its generated code, it gets scanned by codenarc.  I can't seem to get codenarc to exclude the gradletest sourceset for some reason and the generated code fails the check.  Perhaps there is something you can do on your side to disable codenarc for the sourceset?  Maybe as simple as publishing the configs in the manual to disable it.

**Comment by ysb33r** [comment]
For now try adding 

```groovy
codenarcGradleTest.enabled = false
```

and let me know if it works for you.

**Comment by ysb33r** [comment]
@scphantm Did that solution work?
